### PR TITLE
Fix nat ports

### PR DESCRIPTION
**Pull request by kasabe28**
# Proposed Changes

- add portsPerNetworkInterface value in natGateway
- modify testcase to check natGateway's portsPerNetworkInterface

### CODE REVIEW

**Comment by afritzler** [comment]
Why don't we make this configuration configurable in the `Infrastructure` spec instead of having such a complex calculation?

**Comment by afritzler** [comment]
Also can you please fix the history of this PR branch. This looks a little bit off.

**Comment by kasabe28** [comment]
> Also can you please fix the history of this PR branch. This looks a little bit off.

Fixed history of PR branch.

**Comment by afritzler** [comment]
/ref https://github.com/onmetal/gardener-extension-provider-onmetal/pull/98

We might want to have a static configuration first.

**Comment by afritzler** [comment]
Closing in favor of #98

**Pull request closed without merging**
